services:
  db:
    ports:
      - "${DB_PORT_HOST_DEV}:5432"

  api:
    ports:
      - "${API_PORT_HOST_DEV}:8000"

  minio:
    ports:
      - "${MINIO_PORT_HOST_DEV}:9000"
      - "${MINIO_CONSOLE_PORT_HOST_DEV}:9001"
